version: 0.1.1
default:
  # Default profile created for data IO access.
  # Add your credentials for the source you use, and delete the rest.
  # AWS
  AWS_ACCESS_KEY_ID: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
  AWS_SECRET_ACCESS_KEY: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
  AWS_SESSION_TOKEN: session_token (Used to generate Redshift credentials)
  AWS_REGION: region
  # Algolia
  ALGOLIA_APP_ID: app_id
  ALGOLIA_API_KEY: api_key
  ALGOLIA_INDEX_NAME: index_name
  # Airtable
  AIRTABLE_ACCESS_TOKEN: token
  # Azure
  AZURE_CLIENT_ID: "{{ env_var('AZURE_CLIENT_ID') }}"
  AZURE_CLIENT_SECRET: "{{ env_var('AZURE_CLIENT_SECRET') }}"
  AZURE_STORAGE_ACCOUNT_NAME: "{{ env_var('AZURE_STORAGE_ACCOUNT_NAME') }}"
  AZURE_TENANT_ID: "{{ env_var('AZURE_TENANT_ID') }}"
  # Chroma
  CHROMA_COLLECTION: collection_name
  CHROMA_PATH: path
  # Clickhouse
  CLICKHOUSE_DATABASE: default
  CLICKHOUSE_HOST: host.docker.internal
  CLICKHOUSE_INTERFACE: http
  CLICKHOUSE_PASSWORD: null
  CLICKHOUSE_PORT: 8123
  CLICKHOUSE_USERNAME: null
  # Druid
  DRUID_HOST: hostname
  DRUID_PASSWORD: password
  DRUID_PATH: /druid/v2/sql/
  DRUID_PORT: 8082
  DRUID_SCHEME: http
  DRUID_USER: user
  # DuckDB
  DUCKDB_DATABASE: database
  DUCKDB_SCHEMA: main
  # Google
  default: 
      GOOGLE_SERVICE_ACC_KEY:
        type: service_account
        project_id: winter-pivot-457709-k5
        private_key_id: c951cf4eb11ad0539d24dba8621b6a06399fd91e
        private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDNS2LO2nFxrHD1\nAM18TxMAeG6OqWRcN+UFg6yxpm/uf9sJvgSdDhcOtFx3E+2ncXkh2apOBmoKOEh6\nrsY4EumpaWsOhq1LJRLk+359sRx9GQENVPM4kj4Bk6gmqFODV/D66G638OZNq/fZ\nGI7BNv57FY92eUKCxaaHeQ2zbRYvRnQwtNqBoNG7VXMEmrZEsySjJptaR2TMBv1I\n+tkRavT+4Zplts3X8nGea0wNknmWrPFmRDDd5A8j7TOkHxXCbtG1pr8e5XRSlymK\nJfS92YFZSpHRLytWc9T2vq7MmegjRvFQx3tMm9jy/ig108Fsb4dHH212cnLvk8x2\nSskvfnT1AgMBAAECggEABAAeJ2FBg4FPJzBnkK6ldGV5uWJ1ep2P4y+0b7bKU20J\nj+hJxI9ies51cdBBLzmKbn2EcHuhWTHNFG+aRxFJR9xDx4yaImQmeNtUv5lyBcG1\nD/Ux6HjjEpqgaiEZatkNxgSS/xcc6ce6L0W8/Gi4WfOAMEMUfSIMXh30BXp7S5sB\n19dXqWABbsywlKHwBJ/wXJ5sBBjFDcfku8JUixSWbw2HXkEn/farqhEKedAPBjGZ\nPaM0h94T4YZwSBlXa1barV5mjI6rInfwv0YTDd2ztYYSnGfQVXPFJ+zStt7zk98C\nHFytBPBOsELiLoTQCIARjM9vfTqy1U0djz51MzUrgQKBgQDlzuInuXWALV0j2e29\n7AGEifqmsJ4UPU0FYHUUZxfKDAxOJSLj8ozO/OeEHFEywg19MaJ0u3mxNrHEmiM+\nhRLelckOZ1btxmGyVteCk5ZAtodK9B/cBaBX9GVDFasnXv/pe8NIQsULvN5ifiIx\n/vjDejDnGCqgQ+ACv1fUidOOgQKBgQDksURXEBD2r70y0iucpEZRH5zrY0s8oqYn\nWkCVW9YljuVzUWUB6QGMXbggCgElgQ7SH1POmGVfXAEFyqozevpslwnkCtpgbvXk\n8OQJtKS56sD6XDbvgsktMDD3pQZ76XYxEZSV38LdM2dL9atV7xsLuNJ3vD2Nvz2L\n3lXXmQxUdQKBgGnyVSVHRTqQr24F3KtAkPqPujT7HAXstQOTkqaTWM5Xe5zTViCN\nBAmxYvLvMygZeqqLJYB3pgTjWFVxUmpSY36mw4iWb+czHHthuf2DGTRAcmNF5SJE\nncWu8Lha1wtRqt3zpvY7giiFLGlwCUfPatSEEuOXqp80a6QYnt9no1cBAoGAYBHj\nvps+NRMwbMgDkCMmcu/P0MZ+lbNSD1gHp3bT6CU2WJJJ11qVzuyT68moH6QuoLCO\nWUyF0WBqAY/YnhW8W5+7hPPWNwqF+64Cbd1YEc3/UW0pmsYbUwNanr3Rkn5Jq2VS\nQP+l8ZyleTBz0H7Iosz6hVgrl39OEJLPBuoBVv0CgYA7JEXFiUuRNOwyP8aeIXcm\nh2V3gNXo8EWRz5yz4NsJgjFWn/DbwtYHIsguFZo9oMsSWZCXemrxxRdtlYLUwPNm\nRPYk80xh7bWvHxTpmA7P17AS3fXGpUYZQRZHJ4E4et/7P1dlwpBd5CeDtwF8RaA6\nntRRyTqQsNte7KFc+BOxlw==
        client_email: terraform-runner@winter-pivot-457709-k5.iam.gserviceaccount.com
        client_id: 1234567890
        auth_uri: https://accounts.google.com/o/oauth2/auth
        token_uri: https://oauth2.googleapis.com/token
        auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
        client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/terraform-runner%40winter-pivot-457709-k5.iam.gserviceaccount.com
      GOOGLE_SERVICE_ACC_KEY_FILEPATH: ~/Users/Adi/.gc/gcp_service_capstone.json
      GOOGLE_LOCATION: US

  # MongoDB
  # Specify either the connection string or the (host, password, user, port) to connect to MongoDB.
  MONGODB_CONNECTION_STRING: "mongodb://{username}:{password}@{host}:{port}/"
  MONGODB_HOST: host
  MONGODB_PORT: 27017
  MONGODB_USER: user
  MONGODB_PASSWORD: password
  MONGODB_DATABASE: database
  MONGODB_COLLECTION: collection
  # MSSQL
  MSSQL_DATABASE: database
  MSSQL_SCHEMA: schema
  MSSQL_DRIVER: "ODBC Driver 18 for SQL Server"
  MSSQL_HOST: host
  MSSQL_PASSWORD: password
  MSSQL_PORT: 1433
  MSSQL_USER: SA
  # MySQL
  MYSQL_DATABASE: database
  MYSQL_HOST: host
  MYSQL_PASSWORD: password
  MYSQL_PORT: 3306
  MYSQL_USER: root
  # Pinot
  PINOT_HOST: hostname
  PINOT_PASSWORD: password
  PINOT_PATH: /query/sql
  PINOT_PORT: 8000
  PINOT_SCHEME: http
  PINOT_USER: user
  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: postgres
  POSTGRES_SCHEMA: public # Optional
  POSTGRES_USER: username
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: hostname
  POSTGRES_PORT: 5432
  # Qdrant
  QDRANT_COLLECTION: collection
  QDRANT_PATH: path
  # Redshift
  REDSHIFT_SCHEMA: public # Optional
  REDSHIFT_DBNAME: redshift_db_name
  REDSHIFT_HOST: redshift_cluster_id.identifier.region.redshift.amazonaws.com
  REDSHIFT_PORT: 5439
  REDSHIFT_TEMP_CRED_USER: temp_username
  REDSHIFT_TEMP_CRED_PASSWORD: temp_password
  REDSHIFT_DBUSER: redshift_db_user
  REDSHIFT_CLUSTER_ID: redshift_cluster_id
  REDSHIFT_IAM_PROFILE: default
  # Snowflake
  SNOWFLAKE_USER: username
  SNOWFLAKE_PASSWORD: password
  SNOWFLAKE_ACCOUNT: account_id.region
  SNOWFLAKE_DEFAULT_WH: null                  # Optional default warehouse
  SNOWFLAKE_DEFAULT_DB: null                  # Optional default database
  SNOWFLAKE_DEFAULT_SCHEMA: null              # Optional default schema
  SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: null      # Optional private key passphrase
  SNOWFLAKE_PRIVATE_KEY_PATH: null            # Optional private key path
  SNOWFLAKE_ROLE: null                        # Optional role name
  SNOWFLAKE_TIMEOUT: null                     # Optional timeout in seconds
  # Trino
  trino:
    catalog: postgresql                       # Change this to the catalog of your choice
    host: 127.0.0.1
    http_headers:
      X-Something: 'mage=power'
    http_scheme: http
    password: mage1337                        # Optional
    port: 8080
    schema: core_data
    session_properties:                       # Optional
      acc01.optimize_locality_enabled: false
      optimize_hash_generation: true
    source: trino-cli                         # Optional
    user: admin
    verify: /path/to/your/ca.crt              # Optional
  # Weaviate
  WEAVIATE_ENDPOINT: https://some-endpoint.weaviate.network
  WEAVIATE_INSTANCE_API_KEY: YOUR-WEAVIATE-API-KEY
  WEAVIATE_INFERENCE_API_KEY: YOUR-OPENAI-API-KEY
  WEAVIATE_COLLECTION: collectionn_name
